Використай цей шаблон в роботі з датасетом.      
Ти можеш додавати комірки за потреби, але не змінюй структуру і послідовність питань.      
Обмежся функціями з наведених бібліотек.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

1. Завантаж датасет з бібліотеки seaborn:

In [2]:
titanic = sns.load_dataset("titanic")

2. Переглянь перші рядки датасету. Зроби висновок, чи коректно він завантажився.

In [34]:
titanic.head()
#дані завантажились коректно

,survived,pclass,sex,age,fare,embarked,class,who,adult_male,deck,embark_town,alive,relatives,relatives_category,age_category,Death
0,0,3,male,22.0,7.2500,S,Third,man,True,Unknown,Southampton,no,1,1,young,True
1,1,1,female,38.0,71.2833,C,First,woman,False,C,Cherbourg,yes,1,1,adult,False
2,1,3,female,26.0,7.9250,S,Third,woman,False,Unknown,Southampton,yes,0,0,young,False
3,1,1,female,35.0,53.1000,S,First,woman,False,C,Southampton,yes,1,1,adult,False
4,0,3,male,35.0,8.0500,S,Third,man,True,Unknown,Southampton,no,0,0,adult,True

3. Перевір типи стовпців. Які з них потребують перетворення?

In [33]:
titanic.info()
#є кілька стовпців з типом object, які можна перетворити, а також колонку age можна перевести у тип int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survived            891 non-null    int64
 1   pclass              891 non-null    int64
 2   sex                 891 non-null    object
 3   age                 891 non-null    float64
 4   fare                891 non-null    float64
 5   embarked            889 non-null    object
 6   class               891 non-null    category
 7   who                 891 non-null    object
 8   adult_male          891 non-null    bool
 9   deck                891 non-null    object
 10  embark_town         889 non-null    object
 11  alive               891 non-null    object
 12  relatives           891 non-null    int64
 13  relatives_category  891 non-null    object
 14  age_category        891 non-null    object
 15  Death               891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(3), object(8)
memory usage: 93.4+ KB

4. Перевір статистику по УСІМ стовпцям датасету.

In [5]:
titanic.describe(include = 'all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

5. Необхідно створити єдиний стовпчик, що вказує кількість родичів для кожного пасажира на борту, замість:
- кількість братів/сестер або чоловіків/дружин на борту;
- кількість батьків або дітей на борту;

Булева ознака: стовпчик 'alone'=True, якщо пасажир подорожував один (без родичів на борту).        
Перевір, щоб для одиноких пасажирів новий стовпчик мав значення 0.      
Після створення нового стовпчика, дропни "sibsp", "parch", "alone".     
Результат представ у вигляді підрахунку кількості пропущених значень (NaN) у стовпці relatives.

In [6]:
titanic['relatives'] = titanic['sibsp'] + titanic['parch']
titanic = titanic.drop(['sibsp', 'parch','alone'], axis=1)
titanic['relatives'].isna().sum()

np.int64(0)

6. Перевір, як часто зустрічається певна кількість родичів в новому стовпці.    
Результат представ у вигляді таблиці, побудованої з використанням групування та агрегації:

In [7]:
titanic_relatives = titanic.groupby('relatives')['relatives'].count()
titanic_relatives

relatives
0     537
1     161
2     102
3      29
4      15
5      22
6      12
7       6
10      7
Name: relatives, dtype: int64

7. Використовуючи цикл заміни кількість родичів, що перевищує число 5(п'ять) на значення "above 5"(понад п'ять).       
Запиши значення в новий стовпчик ʼrelatives_categoryʼ.     
Результат представ у вигляді таблиці, побудованої з використанням групування та агрегації:

In [8]:
titanic['relatives_category'] = titanic['relatives'].astype(object)

for i in range(len(titanic)):
    if pd.to_numeric(titanic.loc[i, 'relatives_category'], errors='coerce') > 5:
        titanic.loc[i, 'relatives_category'] = 'above 5'

titanic_сategory = titanic.groupby('relatives_category')['relatives_category'].count()
titanic_сategory

relatives_category
0          537
1          161
2          102
3           29
4           15
5           22
above 5     25
Name: relatives_category, dtype: int64

8. Необхідно вивести на екран статистику по відсотковому показнику пасажирів з кількістю родичів більше 5 відносно загального числа пасажирів для кожного з міст посадки. Для цього:
- порахуй загальну кількість пасажирів в кожному з міст посадки,
- знайди число пасажирів з кількістю родичів більше 5 в кожному з міст посадки,
- поділи ці два стовчики між собою, перетворивши результат у відсотки (ціле число).        
Відобрази статистику порахованих показників, згруповану по містах посадки.

In [9]:
titanic_filtered = titanic[titanic['relatives_category'] == "above 5"]

titanic_city1 = titanic.groupby('embark_town')['embark_town'].count()
titanic_city2 = titanic_filtered.groupby('embark_town')['embark_town'].count()
titanic_stats = (titanic_city2/titanic_city1*100).round(0)
titanic_stats

embark_town
Cherbourg      NaN
Queenstown     NaN
Southampton    4.0
Name: embark_town, dtype: float64

9. Заповни відсутні значення віку медіаною.

In [12]:
median_age = titanic['age'].median()

for d in range(len(titanic)):
    if pd.isna(titanic.loc[d, 'age']):
        titanic.loc[d, 'age'] = median_age

titanic['age'].isna().sum()

np.int64(0)

10. Створи новий стовпець, де вік представлено категорією, замість числа (наприклад: до 14 років, 14-34 роки, 35-59 років, 60 і більше років). Виконай задачу з використанням користувацької функції. Осіб з невідомим віком познач відповідно.

In [10]:
def create_category(age):
    if pd.isna(age):
        return 'unknown'
    elif age <= 14:
        return 'children'
    elif age < 35:
        return 'young'
    elif age < 60:
        return 'adult'
    else:
        return 'old'
        
titanic['age_category'] = titanic['age'].apply(create_category)        
titanic['age_category']

0        young
1        adult
2        young
3        adult
4        adult
        ...
886      young
887      young
888    unknown
889      young
890      young
Name: age_category, Length: 891, dtype: object

11. Перевір, в якій віковій категорії була найвища смертність.     
Для цього рекомендується перетворити стовпець 'alive' в булевий тип.    
 Потім підрахувати загальну кількість пасажирів та кількість тих, хто не вижив.      
 Потім обчисли відносний показниках для кожної категорії.

In [15]:
titanic['Death'] = titanic['alive'] == 'no'
total = titanic.groupby('age_category')['age_category'].count()
deaths = titanic.groupby('age_category')['Death'].sum()
mortality_rate = (deaths / total * 100).round(2)

result = pd.DataFrame({
    'total': total,
    'deaths': deaths,
    'mortality_rate (%)': mortality_rate
})

result

              total  deaths  mortality_rate (%)
age_category
adult           209     122               58.37
children         77      32               41.56
old              26      19               73.08
unknown         177     125               70.62
young           402     251               62.44

*Бонусне завдання*         :          
Підготуй розгорнуту статистику смертності по категорії віку, класу квитка, рівню каюти та кількості родичів.      
Які фактори, на твою думку, найбільше пов'язані з рівнем смерності? (наприклад: найбільша смертність у відсотковому значенні спостерігається серед вікової групи ... класу квитка.... при наявності ... родичів та для рівня каюти.... Фактор ... має найвищий вплив на смертність)

In [39]:
total = titanic.groupby('age_category')['age_category'].count()
deaths = titanic.groupby('age_category')['Death'].sum()
mortality_rate = (deaths / total * 100).round(2)

result = pd.DataFrame({
    'total': total,
    'deaths': deaths,
    'mortality_rate (%)': mortality_rate
})
result = result.sort_values('mortality_rate (%)', ascending=False)

print('Death by class category:\n', result, '\n')

total = titanic.groupby('pclass')['pclass'].count()
deaths = titanic.groupby('pclass')['Death'].sum()
mortality_rate = (deaths / total * 100).round(2)

pclass_result = pd.DataFrame({ 'total': total,
    'deaths': deaths,
    'mortality_rate (%)': mortality_rate
})
pclass_result = pclass_result.sort_values('mortality_rate (%)', ascending=False)

print('Death by pclass:\n', pclass_result, '\n')

titanic['deck'] = titanic['deck'].astype(object).fillna('Unknown')
total = titanic.groupby('deck')['Death'].count()
deaths = titanic.groupby('deck')['Death'].sum()
mortality_rate = (deaths / total * 100).round(2)

deck_result = pd.DataFrame({
    'total': total,
    'deaths': deaths,
    'mortality_rate (%)': mortality_rate
})
deck_result = deck_result.sort_values('mortality_rate (%)', ascending=False)

print('Death by deck:\n', deck_result, '\n')


total = titanic.groupby('relatives')['Death'].count()
deaths = titanic.groupby('relatives')['Death'].sum()
mortality_rate = (deaths / total * 100).round(2)

relatives_result = pd.DataFrame({
    'total': total,
    'deaths': deaths,
    'mortality_rate (%)': mortality_rate
})
relatives_result = relatives_result.sort_values('mortality_rate (%)', ascending=False)

print('Death by Relatives:\n', relatives_result, '\n')


total = titanic.groupby('who')['Death'].count()
deaths = titanic.groupby('who')['Death'].sum()
mortality_rate = (deaths / total * 100).round(2)

Death by class category:
               total  deaths  mortality_rate (%)
age_category
old              26      19               73.08
unknown         177     125               70.62
young           402     251               62.44
adult           209     122               58.37
children         77      32               41.56

Death by pclass:
         total  deaths  mortality_rate (%)
pclass
3         491     372               75.76
2         184      97               52.72
1         216      80               37.04

Death by deck:
          total  deaths  mortality_rate (%)
deck
Unknown    688     482               70.06
A           15       8               53.33
G            4       2               50.00
C           59      24               40.68
F           13       5               38.46
B           47      12               25.53
E           32       8               25.00
D           33       8               24.24

Death by Relatives:
            total  deaths  mortality_rate (%)
relatives
7              6       6              100.00
10             7       7              100.00
5             22      19               86.36
4             15      12               80.00
0            537     374               69.65
6             12       8               66.67
1            161      72               44.72
2            102      43               42.16
3             29       8               27.59

Можна констатувати що опираючись на дані які ми отримали, 
рівень смертності був найвищий серед людей старшого віку, та серед тих які мали нижчий клас квитка.
Саме ці два фактори мали вирішальну роль.